GET http://localhost:3003/blogs

###
GET http://localhost:3003/blogs/642f7d114f8eeb92e2c7e0a2

###
GET http://localhost:3003/blogs/642f7db74f8eeb92e2c7e0a6

###
DELETE http://localhost:3003/blogs/6435a921f6e5bf87df05e781
Authorization: bearer xxx.yyy.zzz

###
Get http://localhost:3003/info

###
POST http://localhost:3003/blogs
Content-Type: application/json
Authorization: bearer xxx.yyy.zzz

{
  "title": "Middleware Myths",
  "author": "Tim Zhang",
  "url": "zhang.com",
  "likes": 9876,
  "user": "64345c2961642d12ac0a45fe"
}

###
PUT http://localhost:3003/blogs/642f7d114f8eeb92e2c7e0a2
Content-Type: application/json

{
  "title": "Stock Markt Update",
  "author": "Tom King",
  "url": "bloomberg.com",
  "likes": 1024
}

###
POST http://localhost:3003/users
Content-Type: application/json

{
  "username": "tzhang",
  "name": "T Zhang",
  "password": "password"
}

###
GET http://localhost:3003/users

###
POST http://localhost:3003/login
Content-Type: application/json

{
  "username": "tzhang",
  "password": "password"
}
