GET http://localhost:3003/blogs

###
GET http://localhost:3003/blogs/642f7d114f8eeb92e2c7e0a2

###
GET http://localhost:3003/blogs/642f7db74f8eeb92e2c7e0a6

###
DELETE http://localhost:3003/blogs/4

###
Get http://localhost:3003/info

###
POST http://localhost:3003/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InR6aGFuZyIsImlkIjoiNjQzNDVjMjk2MTY0MmQxMmFjMGE0NWZlIiwiaWF0IjoxNjgxMjIzNTM5fQ.DKmpZWnGLE1MWkaS0R3qzSvkZlw_9YIaP3qta8SsVo4

{
  "title": "Daily Math Problems",
  "author": "Tim Zhang",
  "url": "zhang.com",
  "likes": 1098,
  "user": "64345c2961642d12ac0a45fe"
}

###
PUT http://localhost:3003/blogs/642f7d114f8eeb92e2c7e0a2
Content-Type: application/json

{
  "title": "Stock Markt Update",
  "author": "Tom King",
  "url": "bloomberg.com",
  "likes": 1024
}

###
POST http://localhost:3003/users
Content-Type: application/json

{
  "username": "tzhang",
  "name": "T Zhang",
  "password": "password"
}

###
GET http://localhost:3003/users

###
POST http://localhost:3003/login
Content-Type: application/json

{
  "username": "tzhang",
  "password": "password"
}
